### PR TITLE
Use PyGlossary to generate StarDict glossaries

### PR DESCRIPTION
**Pull request by ilius**
Implement #21

Tested by running `make stardict` inside [eng-ara](https://github.com/freedict/fd-dictionaries/tree/master/eng-ara), it generates StarDict files (`eng-ara.ifo eng-ara.dict.dz eng-ara.idx.gz`). And validated by converting the StarDict to Tabfile.

I wasn't sure about virtualenv instructions on README so I didn't write it.

### CODE REVIEW

**Comment by humenda** [comment]
First of all, apologies for the delay! From now in I'll answer in time :-).

My findings:

-   Plese remove the unused `stardict_prefix`.
-   Build files should end up in `build<platform` name>, i.e. build/stardict.
-   The build should be invoked using `make build-<platformname>`, i.e. `make
    build-stardict`.
-   `clean` should not leave files behind (here: pyglossary*.out`, though that's
    fixed by moving it to build/stardict.
-   Stardict is not a platform, that means:
    -   `make list-platforms` doesn't list stardict.
    -   `make` (i.e. make all) doesn't build stardict
    -   Releasing doesn't work out-of-the-box
    -   Just rename the build rule (see above) and add stardict to
        `available_platforms`.

Would it be ok to prepare a fix? thanks!

**Comment by humenda** [comment]
Virtualenv: If you would like to write up some instructions, this would be
appreciated. Would you be so kind to add this to the wiki? It's here:
<https://github.com/freedict/fd-dictionaries/wiki/FreeDict-HOWTO-%E2%80%93-FreeDict-Build-System>.
Thanks

**Comment by ilius** [comment]
Updated.

Should we instruct users to create a new env for stardict?
I kinda find it unnecessary to copy the venv instructions for every format.
People can use venv for anything they want.

**Comment by ilius** [comment]
I made some changes to https://github.com/freedict/fd-dictionaries/wiki/Dictionary-Formats#stardict

**Comment by humenda** [comment]
I would probably suggest (and use) a FD venv, i.e. for tools + stardict.

**Comment by ilius** [comment]
What's FD?
You mean combine instructions of slob and stardict?

**Comment by humenda** [comment]
FD is really just slang for FreeDict :). I meant documenting and implementing
Stardict as a format, same as slob. So it is meantioned in the HOWTO, it is
documented with `make help` and `make list-platforms` and maybe in the readme
of tools if formats are mentioned (didn't check).

**Pull request merged**
